pool:
  name: Azure Pipelines

jobs:
- job: Test
  pool:
    vmImage: 'windows-2019'
  steps:
  # - task: PowerShell@2
  #   env:
  #     CX_APIKEY: $(CX_APIKEY)
  #   inputs:
  #     targetType: 'inline'
  #     script: './cx.exe scan create -s . --project-name myadotest --branch main --debug'

  - task: Checkmarx AST@2
    inputs:
      CheckmarxService: 'EU PROD21'
      projectName: '$(Build.Repository.Name)'
      branchName: '$(Build.SourceBranchName)'
      tenantName: 'cxast_rnd_projects_scans'
      additionalParams: '--debug'